<div class="item-showcase">
<?php foreach ($attachments as $attachment): ?>
    <div class="item resource">
    <?php
    $item = $attachment->item();
    if ($item):
    ?>
        <?php
               $media = $attachment->media() ? : $item->primaryMedia();
               $mediaRenderer = $media->renderer();
               if ($media && $mediaRenderer !== 'iiif') :
                   echo $media->render([
                   'thumbnailType' => $thumbnailType,
                   'link' => $link,
               ]);
               elseif ($media) :
                   echo $item->linkRaw($this->thumbnail($media, $this->thumbnailType));
               endif;
               ?>
        <?php $showTitleOption = $this->showTitleOption; ?>
        <?php if ($showTitleOption == 'item_title'): ?>
        <div class="top-level-metadata">
        <h3><?php echo $item->link($item->displayTitle()); ?></h3>
        <?php elseif ($showTitleOption == 'file_name'): ?>
        <h3><?php echo $media->displayTitle(); ?></h3>
        <?php endif; ?>
    <?php endif; ?>
    <?php if ($item->value('dcterms:date')) ?>
    <p class="date"><?php echo $item->value('dcterms:date'); ?></p>
    <?php if ($item->value('dcterms:alternative')) ?>
    <p class="alt_title"><?php echo $item->value('dcterms:alternative'); ?></p>
      </div>
    <?php
    $caption = $attachment->caption();
    if ($caption):
    ?>
        <div class="caption"><?php echo $caption; ?></div>
    <?php endif; ?>
    <p class="identifier"><?php echo "Ref. " . $item->value('dcterms:identifier'); ?></p>
    </div>
<?php endforeach; ?>
</div>
