  <?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->appendStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet($this->assetUrl('css/uom_footer.css'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;700&display=swap');
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('js/langselect.js'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$this->jsTranslate();
$userBar = $this->userBar();
$banner = $this->themeSettingAssetUrl('banner');
$bannerWidth = ($this->themeSetting('banner_width')) ? $this->themeSetting('banner_width') : '';
$bannerHeight = $this->themeSetting('banner_height');
$bannerHeightMobile = $this->themeSetting('banner_height_mobile');
$bannerPosition = ($this->themeSetting('banner_position')) ? str_replace('_','-', $this->themeSetting('banner_position')) : 'center';
?>

<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php if ($this->themeSetting('accent_color') !== '' || $this->themeSetting('nav_color') !== ''): ?>
        <style>
            <?php if ($accentColor = $this->themeSetting('accent_color')): ?>
            a {
                color: <?php echo $accentColor; ?>
            }

            input[type="submit"]:hover,
            button:hover,
            .button:hover,
            .sub-menu a:hover,
            .site-page-pagination a:hover,
            a.advanced-search:hover {
                background-color: <?php echo $accentColor; ?>
            }
            <?php endif; ?>

            <?php if ($navColor = $this->themeSetting('nav_color')): ?>
            .oc-menu {
                background-color: <?php echo $navColor; ?>
            }
            <?php endif; ?>

            .banner {
                height: <?php echo ($bannerHeight !== '') ? $bannerHeight: 'auto'  ?>;
                align-items: <?php echo $bannerPosition; ?>;
            }
            <?php if ($bannerHeightMobile !== ''): ?>
                @media screen and (max-width:640px) {
                    .banner {
                        height: <?php echo $bannerHeightMobile; ?>;
                    }
                }
            <?php endif; ?>
        </style>
        <?php endif; ?>
        <?php echo $this->headScript(); ?>
    </head>

    <?php echo $this->htmlElement('body'); ?>
            <div id="oc-container" class="oc-container">
                <div class="oc-pusher">
                    <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
                    <?php echo $userBar; ?>
                        <header role="banner">
                            <div class="header_top">
                                    <a href="http://www.manchester.ac.uk/library"><img src="/files/asset/uom_logo.png" alt="The University of Manchester Library logo" class="university-logo"/></a>
                                <div class="site-heading"><p>Manchester Digital Exhibitions</p></div>
                                <div class="full-screen-search">
                                    <?php echo $this->partial('common/search-form'); ?>
                                </div>
                                <div id="lang">
                                <?php if ($this->getHelperPluginManager()->has('languageSwitcher')) echo $this->languageSwitcher([ 'locale_as_code' => true ]); ?>
                                </div>
                                <div id="oc-trigger">
                                    <button id="menu-button" class="o-icon-menu" data-effect="oc-push" aria-label="<?php echo $this->translate('Menu'); ?>"></button>
                                    <nav id="menu" class="oc-menu oc-push" role="navigation">
                                        <?php echo $site->publicNav()->menu()->renderMenu(); ?>
                                    </nav>
                                </div>
                            </div>
                            <div id="navbar" class="navbar">
                                <h1>
                                    <a href="<?php echo $site->url(); ?>">
                                        <?php echo $escape($siteTitle); ?>
                                    </a>
                                </h1>
                                <nav id="top-menu" role="navigation" aria-label="top menu">
                                    <?php echo $site->publicNav()->menu()->renderMenu(); ?>
                                </nav>
                            </div>
                        </header>
                        <div class="oc-content">
                            <div class="oc-content-inner">
                                <main id="content" role="main">
                                    <?php echo $this->content; ?>
                                </main>
                            </div>
                        </div>
                    <footer class="footerContainer">							
                        <div class="row tripleVertPadding">     
                            <div class="fourcol halfSizeUntilLargeMobile">
                                <div class="footerLogos">
                                    <img src="https://www.library.manchester.ac.uk/assets/images/design/national-research-libraries.png" height="63" alt="National Research Libraries">											
                                    <p>The University of Manchester Library is one of five National Research Libraries</p>
                                </div>
                            </div>
                            <div class="fourcol halfSizeUntilLargeMobile lastAtMobile contact">
                                <h2>Get in touch</h2>
                                <p>In our efforts to improve this site, <a href="#">we welcome your thoughts, questions, and feedback.</a></p>
                            </div>
                            <div class="fourcol last">
                                <h2>Connect with us</h2>
                                <ul class="inlineList footer-socialIcons">                
                                    <li><a href="https://www.facebook.com/pages/The-University-of-Manchester-Library/25777209922">
                                        <img class="lazy" src="https://www.library.manchester.ac.uk/assets/images/design/icon-facebook-large.png" width="40" height="40" data-original="/assets/images/design/icon-facebook-large.png" alt="Facebook page for The University of Manchester Library">
                                        <noscript><img class="" src="https://www.library.manchester.ac.uk/assets/images/design/icon-facebook-large.png" width="40" height="40" alt="Facebook page for The University of Manchester Library"></noscript>
                                        </a>
                                    </li>
                                    <li><a href="https://twitter.com/UoMLibrary">
                                        <img class="lazy" src="https://www.library.manchester.ac.uk/assets/images/design/icon-twitter-large.png" width="40" height="40" data-original="/assets/images/design/icon-twitter-large.png" alt="Twitter page for The University of Manchester Library">
                                        <noscript><img class="" src="https://www.library.manchester.ac.uk/assets/images/design/icon-twitter-large.png" width="40" height="40" alt="Twitter page for The University of Manchester Library"></noscript>
                                        </a>
                                    </li>
                                    <li><a href="https://www.instagram.com/uomlibrary/">
                                        <img class="lazy" src="https://www.library.manchester.ac.uk/assets/images/design/icon-instagram.png" width="40" height="40" data-original="/assets/images/design/icon-instagram.png"  alt="Instagram page for The University of Manchester Library">
                                        <noscript><img class="" src="https://www.library.manchester.ac.uk/assets/images/design/icon-instagram.png" width="40" height="40" alt="Instagram page for The University of Manchester Library"></noscript>
                                        </a>
                                    </li>
                                    <li><a href="https://www.youtube.com/user/UoMLibrary">
                                        <img class="lazy" src="https://www.library.manchester.ac.uk/assets/images/design/icon-youtube-large.png" width="40" height="40" data-original="/assets/images/design/icon-youtube-large.png"  alt="YouTube page for The University of Manchester Library">
                                        <noscript><img class="" src="https://www.library.manchester.ac.uk/assets/images/design/icon-youtube-large.png" width="40" height="40" alt="YouTube page for The University of Manchester Library"></noscript>
                                        </a>
                                    </li>
                                    <li><a href="https://www.linkedin.com/showcase/the-university-of-manchester-library">
                                        <img class="lazy" src="https://www.library.manchester.ac.uk/assets/images/design/icon-linkedin.png" width="40" height="40" data-original="/assets/images/design/icon-linkedin.png"  alt="LinkedIn page for The University of Manchester Library">
                                        <noscript><img class="" src="https://www.library.manchester.ac.uk/assets/images/design/icon-linkedin.png" width="40" height="40" alt="LinkedIn page for The University of Manchester Library"></noscript>
                                        </a>
                                    </li>													
                                </ul>
                            </div>
                        </div>
                        <hr>       
                        <div class="row singleVertPadding">
                            <div class="twelvecol">
                                <ul class="inlineList">
                                    <li><a href="https://www.manchester.ac.uk/disclaimer/">Disclaimer</a> /</li>
                                                <li><a href="https://www.manchester.ac.uk/discover/privacy-information/data-protection/">Data Protection</a> /</li>
                                                <li><a href="https://www.manchester.ac.uk/copyright/">Copyright notice</a> /</li>
                                                <li><a href="https://www.library.manchester.ac.uk/accessibility/manchester-digital-exhibitions/">Web accessibility</a> /</li>
                                                <li><a href="https://www.manchester.ac.uk/discover/privacy-information/freedom-information/">Freedom of information</a> /</li>
                                                <li><a href="https://www.manchester.ac.uk/discover/governance/charitable-status/">Charitable status</a> /</li>             
                                    <li>Royal Charter Number: RC000797</li>
                                </ul>
                            </div>
                        </div>  
                    </footer>      
        <script type="text/javascript" src="<?php echo $this->assetUrl('js/offcanvas.js'); ?>"></script>
    </body>
</html>
