  <?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/uom_footer.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Lora:400,400italic,700,700italic|Bitter:700');
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$this->jsTranslate();
$userBar = $this->userBar();
$banner = $this->themeSettingAssetUrl('banner');
$bannerWidth = ($this->themeSetting('banner_width')) ? $this->themeSetting('banner_width') : '';
$bannerHeight = $this->themeSetting('banner_height');
$bannerHeightMobile = $this->themeSetting('banner_height_mobile');
$bannerPosition = ($this->themeSetting('banner_position')) ? str_replace('_','-', $this->themeSetting('banner_position')) : 'center';
?>

<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php if ($this->themeSetting('accent_color') !== '' || $this->themeSetting('nav_color') !== ''): ?>
        <style>
            <?php if ($accentColor = $this->themeSetting('accent_color')): ?>
            a {
                color: <?php echo $accentColor; ?>
            }

            input[type="submit"]:hover,
            button:hover,
            .button:hover,
            .sub-menu a:hover,
            .site-page-pagination a:hover,
            a.advanced-search:hover {
                background-color: <?php echo $accentColor; ?>
            }
            <?php endif; ?>

            <?php if ($navColor = $this->themeSetting('nav_color')): ?>
            .oc-menu {
                background-color: <?php echo $navColor; ?>
            }
            <?php endif; ?>

            .banner {
                height: <?php echo ($bannerHeight !== '') ? $bannerHeight: 'auto'  ?>;
                align-items: <?php echo $bannerPosition; ?>;
            }
            <?php if ($bannerHeightMobile !== ''): ?>
                @media screen and (max-width:640px) {
                    .banner {
                        height: <?php echo $bannerHeightMobile; ?>;
                    }
                }
            <?php endif; ?>
        </style>
        <?php endif; ?>
        <?php echo $this->headScript(); ?>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <div id="oc-container" class="oc-container">
            <div class="oc-pusher">
                <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
                <?php echo $userBar; ?>
                <header role="banner">
                    <a href="http://www.manchester.ac.uk/library" class="university-logo"><img src="https://assets.manchester.ac.uk/corporate/images/design/logo-university-of-manchester.png" alt="The John Rylands Research Institute and Library logo"/></a>
                    <div class="site-heading"><p>Manchester Digital Exhibitions</p></div>
                    <div class="full-screen-search">
                    <?php echo $this->partial('common/search-form'); ?>
                    </div>
                    <div id="oc-trigger">
                        <button id="menu-button" class="o-icon-menu" data-effect="oc-push" aria-label="<?php echo $this->translate('Menu'); ?>"></button>
                    <nav id="menu" class="oc-menu oc-push" role="navigation">
                        <?php echo $site->publicNav()->menu()->renderMenu(); ?>
                    </nav>
                    </div>
                    <h1>
                        <a href="<?php echo $site->url(); ?>" class="site-title">
                        <?php if ($this->themeSetting('logo')): ?>
                            <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                        <?php else: ?>					
                            <?php echo $escape($siteTitle); ?>
                        <?php endif; ?>
                        </a>
                    </h1>
                </header>
                <div class="oc-content">
                   <div class="oc-content-inner">
                       <div id="content-container">
                            <nav id="side-menu" role="navigation" aria-label="side menu">
                                <?php echo $site->publicNav()->menu()->renderMenu(); ?>
                            </nav>
                            <main id="content" role="main">
                                <?php echo $this->content; ?>
                            </main>
                        </div>
                    <footer>
                        <?php if ($footerContent = $this->themeSetting('footer')): ?>
                        <?php echo $footerContent; ?>
                        <?php else: ?>
                            <?php echo $this->translate('Powered by Omeka S'); ?>
                        <?php endif; ?>
                    </footer>
                  </div>
                </div>
            </div>
        </div>
        <script type="text/javascript" src="<?php echo $this->assetUrl('js/offcanvas.js'); ?>"></script>		
<script type='text/javascript'>//<![CDATA[ 
$(function(){
$('img').bind('contextmenu', function(e){
return false;
}); 
});//]]>  
</script>
		
		
    </body>
</html>
